# Generated by Django 3.2 on 2021-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('location', models.CharField(max_length=1024)),
                ('is_working', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
            ],
        ),
    ]
