# Generated by Django 3.2 on 2021-04-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=256)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.pharmacy')),
            ],
            options={
                'db_table': 'distribution',
            },
        ),
    ]
